apiVersion: v1
kind: Pod
metadata:
  name: test-pod
spec:
  serviceAccountName: event-creator-sa
  containers:
  - name: test-container
    image: jonlabelle/network-tools:latest
    command: ["sleep", "infinity"]
    volumeMounts:
    - name: config-volume
      mountPath: /config
  volumes:
  - name: config-volume
    configMap:
      name: prestop-script

