apiVersion: batch/v1
kind: Job
metadata:
  name: example-job
spec:
  template:
    metadata:
      name: test-pod
    spec:
      serviceAccountName: event-creator-sa
      restartPolicy: Never
      containers:
      - name: test-container
        image: jonlabelle/network-tools:latest
        # command: ["sleep", "infinity"]
        # command: ["ls"]
        command: ["/bin/bash", "-c", "for i in {1..10}; do echo hello $i; sleep 1; done"]
        volumeMounts:
        - name: config-volume
          mountPath: /config
      volumes:
      - name: config-volume
        configMap:
          name: prestop-script

